[0m14:54:20.259503 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f38abf10a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f38ab0ad9c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f38ab0ad960>]}


============================== 14:54:20.266035 | 071fb8f7-60e5-4042-a636-cd83760c098a ==============================
[0m14:54:20.266035 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:54:20.267107 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init dbt', 'send_anonymous_usage_stats': 'True'}
[0m14:54:20.273785 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/root/.dbt')}
[0m14:54:20.274621 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:54:47.873209 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/site-packages/dbt/include/starter_project
[0m14:54:47.969716 [info ] [MainThread]: 
Your new dbt project "tuva_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:54:47.970559 [info ] [MainThread]: Setting up your profile.
[0m14:54:59.761436 [info ] [MainThread]: Profile tuva_dbt written to /root/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m14:54:59.763007 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 39.561455, "process_in_blocks": "0", "process_kernel_time": 0.100919, "process_mem_max_rss": "112252", "process_out_blocks": "40", "process_user_time": 1.15462}
[0m14:54:59.763836 [debug] [MainThread]: Command `dbt init` succeeded at 14:54:59.763737 after 39.56 seconds
[0m14:54:59.764550 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f38abf10a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f38ab081210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f38ab2efb50>]}
[0m14:54:59.765286 [debug] [MainThread]: Flushing usage events
[0m14:55:00.208820 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:02:44.787267 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff62d660d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff62c7b9e40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff62c7b9d50>]}


============================== 15:02:44.793173 | a0be2a4d-1007-4d7f-801b-54492aa49fb7 ==============================
[0m15:02:44.793173 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:02:44.794218 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/app/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:02:44.795203 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:02:44.796671 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.07050712, "process_in_blocks": "57720", "process_kernel_time": 0.127465, "process_mem_max_rss": "91936", "process_out_blocks": "1168", "process_user_time": 1.22154}
[0m15:02:44.797488 [debug] [MainThread]: Command `dbt seed` failed at 15:02:44.797392 after 0.07 seconds
[0m15:02:44.798215 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff62d660d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff62c85c490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff62c85c4f0>]}
[0m15:02:44.799076 [debug] [MainThread]: Flushing usage events
[0m15:02:45.168108 [debug] [MainThread]: An error was encountered while trying to flush usage events
